services:
  elasticsearch:
    image: elasticsearch:9.1.5
    container_name: elasticsearch
    restart: "no"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    restart: "no"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  etcd:
    image: quay.io/coreos/etcd:v3.6.5
    container_name: etcd
    restart: "no"
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      ETCD_NAME: "etcd0"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd:2380"
      ETCD_INITIAL_CLUSTER: "etcd0=http://etcd:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"

  milvus:
    image: milvusdb/milvus:2.6-20251018-642a77a4
    container_name: milvus
    depends_on:
      - etcd
      - minio
    restart: "no"
    environment:
      TZ: "UTC"
      ETCD_ENDPOINTS: "http://etcd:2379"
      MILVUS_DEPLOY_MODE: "standalone"
      MILVUS_STANDALONE_MODE: "true"
      MINIO_ADDRESS: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "milvus-bucket"
    volumes:
      - milvus_data:/var/lib/milvus
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530" # gRPC
      - "19121:19121" # REST

volumes:
  es_data:
  minio_data:
  milvus_data:
